version: '3.8'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
    - "27017:27017"
    environment:
      MONGO_INIT DB_ROOT_USERNAME: root
      MONGO_INIT DB_ROOT_PASSWORD: password
      MONGO_INIT DB_DATABASE: product-service
    volumes:
      - ./data:/data/db
